package io.sentry.kotlin.multiplatform

import io.sentry.kotlin.multiplatform.extensions.toCocoaFeedback
import io.sentry.kotlin.multiplatform.protocol.SentryId
import io.sentry.kotlin.multiplatform.protocol.UserFeedback
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * Tests for [toCocoaFeedback]. Full field-level assertions are limited because
 * [CocoaSentryFeedback] only exposes [CocoaSentryFeedback.eventId] through the
 * ObjC bridge — the other properties (message, name, email, source,
 * associatedEventId) are set at construction time but are not readable via
 * the Kotlin/Native ObjC interop layer.
 */
class UserFeedbackExtensionsTest {

    private val sentryIdString = "dcebada57d794590a6da3d1977eed58a"

    @Test
    fun `toCocoaFeedback returns non-null for fully populated feedback`() {
        val userFeedback = UserFeedback(SentryId(sentryIdString)).apply {
            name = "John Doe"
            email = "john@doe.com"
            comments = "I had an error"
        }

        assertNotNull(userFeedback.toCocoaFeedback())
    }

    @Test
    fun `toCocoaFeedback returns non-null for empty feedback with EMPTY_ID`() {
        val userFeedback = UserFeedback(SentryId.EMPTY_ID)

        assertNotNull(userFeedback.toCocoaFeedback())
    }

    @Test
    fun `toCocoaFeedback returns non-null when comments is null`() {
        val userFeedback = UserFeedback(SentryId(sentryIdString))
        // comments is null — extension should use fallback message "(no comment)"

        assertNotNull(userFeedback.toCocoaFeedback())
    }

    @Test
    fun `toCocoaFeedback returns non-null when only email is set`() {
        val userFeedback = UserFeedback(SentryId(sentryIdString)).apply {
            email = "test@email.com"
        }

        assertNotNull(userFeedback.toCocoaFeedback())
    }

    @Test
    fun `toCocoaFeedback returns non-null when only name is set`() {
        val userFeedback = UserFeedback(SentryId(sentryIdString)).apply {
            name = "Test User"
        }

        assertNotNull(userFeedback.toCocoaFeedback())
    }

    @Test
    fun `toCocoaFeedback has an auto-generated eventId`() {
        val userFeedback = UserFeedback(SentryId(sentryIdString)).apply {
            comments = "Test"
        }

        // eventId is the feedback's own ID (auto-generated by SentryFeedback init),
        // not the associatedEventId we supply
        assertNotNull(userFeedback.toCocoaFeedback().eventId())
    }
}
